### PR TITLE
Add German Translation

### PR DESCRIPTION
**Pull request by eknoes**
Add German Translation

### CODE REVIEW

**Comment by eknoes** [comment]
I added the "support" for the german date format dd.MM.yyyy and set it to default for the german translation

**Comment by PedroCarrillo** [comment]
Awesome collaboration. I'm trying to get my friend that knows german to see if the translations are correct. If you have a friend who can comment to verify the correctness of the translations are correct would be of great help as I'm still not sure how to validate new languages other than 1 by 1

**Comment by bruhnth17** [comment]
Hey @PedroCarrillo I'm from germany as well. I read through the german translation and can confirm that they are correct.

**Comment by PedroCarrillo** [comment]
Awesome! Thanks for the confirmation. Hey @eknoes, the PR should point to develop branch as it has some new strings too 👍 same for other Pull requests as I will be working on develop until having next version ready :) Thanks for your collaboration

**Comment by eknoes** [comment]
Changed it! :)

**Pull request merged**
